### ISSUE TITLE
Stl files are out of sync with the fusion 360 model

### ISSUE THREAD

**Issue by snarkeystarkey** [MarginallyClever/sixi-2#13]
Per a discussion on Reddit, The STL files are out of date. I'm happy to see what I can do to help, if anyone has any direction they can offer. :)

**Comment by i-make-robots** [comment]
The fusion 360 latest master files are in the README, and here: https://a360.co/35zKVeh

The process I follow is to hide everything except the parts in one STL file and then export the fusion root component.  That has to be repeated for each STL file.

The STL files will have a *lot* of hidden faces.  I used Blender to select all faces visible from the outside, then invert selection, then delete selection.

**Comment by i-make-robots** [comment]
In a perfect world the origin of each STL file (the 0,0,0 point) is on the axis of rotation for each part.

**Comment by i-make-robots** [comment]
I'm here to help and encourage in any way I can.

**Comment by i-make-robots** [comment]
hey @snarkeystarkey, how is it going?  Please let me know if this still interests you and if there's any way I can help.

**Comment by snarkeystarkey** [comment]
It very much does, but my free time is limited.

**Comment by i-make-robots** [comment]
STLs have been updated and folder also contains recommended print settings.  Please help us by taking pictures of parts if you print them.  Thank you!
