### ISSUE TITLE
swap sensors 4 & 5 on unit 1

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/sixi-2#21]
+ update Makelangelo firmware to remove mention of SIXI_UNIT1 (now deprecated)
+ reload firmware on SIXI unit 1
+ confirm all sensors read well in R-O.

**Comment by i-make-robots** [comment]
When the wires are swapped let me know and I'll do the firmware part.

**Comment by jin-han** [comment]
swapped.
